((asm-mode . ((indent-tabs-mode . t)
              (tab-width . 8)
              (asm-comment-char . ?#)))
 (verilog-mode . ((indent-tabs-mode . nil)
                  (tab-width . 4)
                  (verilog-auto-newline . nil)
                  (verilog-indent-level . 4)
                  (verilog-indent-level-behavioral . 4)
                  (verilog-indent-level-declaration . 4)
                  (verilog-indent-level-module . 4)
                  (verilog-indent-lists . nil))))
